version: '3'
services:
  nginx:
    container_name: nginx
    build: ./nginx/
    image: nginx-transcendence
    env_file:
      - .env
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - django
    networks:
      - transcendence-net
    restart: on-failure
    volumes:
      - django-vol:/var/django/

  django:
    container_name: django
    build: ./django
    image: django-transcendence
    env_file:
      - .env
    expose:
      - 8000
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - transcendence-net
    volumes:
      - django-vol:/var/django/

  redis:
    container_name: redis
    image: redis:latest
    env_file:
      - .env
    restart: unless-stopped
    expose:
      - 6379
    volumes:
      - redis-vol:/data
    networks:
      - transcendence-net

  postgres:
    image: postgres:latest
    container_name: postgres
    env_file:
      - .env
    volumes:
      - postgres-vol:/var/lib/postgresql/data/
    networks:
      - transcendence-net
    depends_on:
      - redis
    restart: unless-stopped
    healthcheck:
      test: pg_isready -U ${POSTGRES_USER}
      interval: 2s
      timeout: 20s
      retries: 10

  serverpong:
    container_name: serverpong
    build: ./serverPong
    image: django-serverpong
    restart: always
    depends_on:
      - django
    env_file:
      - .env
    expose:
      - 10000
    networks:
      - transcendence-net

volumes:
  postgres-vol:
    name: postgres-vol
  django-vol:
    name: django-vol
  redis-vol:
    name: redis-vol

networks:
  transcendence-net:
    name: transcendence-net
    driver: bridge
